In [1]:
import math
import numpy as np
import matplotlib.pyplot as plt

Seja o sistema de equações diferenciais estocásticas definido a seguir:

$
\begin{equation}
    \begin{split}
        dX(t) &= V(t)dt \\
        dY(t) &= \big(-\beta Y(t) + V(t)\big)dt \\
        dV(t) &= \big(-\eta V(t) - f(X(t)) - \alpha Y(t)\big)dt + \sum_{j=1}^m \sigma_j dW_t^j
    \end{split}
\end{equation}
$

In [89]:
def f(X):
    delta = 1.0
    return delta*X**3

In [88]:
def a(param,Z):
    beta, eta, alpha, delta, sigma = param
    return np.array([[Z[2,0]],[-beta*Z[1,0] + Z[2,0]],[-eta*Z[2,0] - f(Z[0,0]) - alpha*Z[1,0]]])

In [115]:
def K(param,Z,zeta,h):
    beta, eta, alpha, delta, sigma = param
    return Z + a(param,Z)*h + h**0.5 * np.array([[0.0],[0.0],[np.dot(sigma,zeta)]])

In [120]:
np.random.seed(100)

m = 1

beta = 1.0
eta = 1.0
alpha = 1.0
delta = 1.0
sigma = np.ones((1,m))

param = [beta, eta, alpha, delta, sigma]

T = 1
N = 2**9
h = T/N
M = 30

tpdist = np.vectorize(lambda x: 0.0 if (x <= 2/3) else 3.0**0.5 if (x > 2/3) and (x <= 5/6) else -(3.0**0.5))

zeta = tpdist(np.random.random((m,M,N)))

Z0 = np.array([[0],[0],[0]])
Zn = Z0*np.ones((3,M))
for j in range(N):
    Zn = Zn + (h/2)*a(param,Zn) + a(param, K(param,Zn,zeta[:,:,j],h)) + np.array([[0.0],[0.0],[np.dot(sigma,zeta[:,:,j])]])


<ipython-input-88-0deed800e523>:3: RuntimeWarning: overflow encountered in power
  return np.array([[Z[2,0]],[-beta*Z[1,0] + Z[2,0]],[-eta*Z[2,0] - delta*Z[0,0]**3 - alpha*Z[1,0]]])
<ipython-input-88-0deed800e523>:3: RuntimeWarning: invalid value encountered in subtract
  return np.array([[Z[2,0]],[-beta*Z[1,0] + Z[2,0]],[-eta*Z[2,0] - delta*Z[0,0]**3 - alpha*Z[1,0]]])
<ipython-input-120-f2296da0c3b2>:25: RuntimeWarning: invalid value encountered in add
  Zn = Zn + (h/2)*a(param,Zn) + a(param, K(param,Zn,zeta[:,:,j],h)) + np.array([[0.0],[0.0],[np.dot(sigma,zeta[:,:,j])]])
<ipython-input-115-dc6ea6d9ec9f>:3: RuntimeWarning: invalid value encountered in add
  return Z + a(param,Z)*h + h**0.5 * np.array([[0.0],[0.0],[np.dot(sigma,zeta)]])


In [121]:
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
